### PR TITLE
Add link to Danish version

### PR DESCRIPTION
**Pull request by LunaTheFoxgirl**
I'm not a rust developer please let me know if I need to change anything lol

### CODE REVIEW

**Comment by bnjbvr** [comment]
Hi, and thanks for the PR! It doesn't build with `cargo build` or `cargo run` or `cargo test` so there might be something that went wrong during the _fourche_ (French for fork).

**Comment by LunaTheFoxgirl** [comment]
I will look in to that _kattepine_ (slang for problem in Danish) when I get time, then

**Comment by LunaTheFoxgirl** [comment]
I appear to have misunderstood what "edition" meant in the Cargo.toml file, so I've fixed that part. Maybe it'll compile now?

**Comment by bnjbvr** [comment]
Hard to say if it works or not, there's no example binary :eyes:

**Comment by LunaTheFoxgirl** [comment]
That part on the other hand is very difficult, I have not written any rust for like 3 years and don't have the time to re-learn. So maybe this PR should be closed then.

**Review by bnjbvr — APPROVED** [review]
Nah, it's fine :-) Thanks, hope you had fun with it!

**Pull request merged**
